project:
  type: website
  output-dir: docs

website:
  title: "Numbers Around Us"
  search: false
  page-footer: "For everybody, not to be fooled by numbers"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Business Intelligence
        href: bi/index.qmd
      - text: Data Science
        href: ds/index.qmd
      - text: Date Philosophy
        href: dp/index.qmd
    tools: 
      - icon: github
        text: Github
        href: https://github.com

format:
  html:
    theme: [cosmo, styles.scss]
    page-layout: full

